export const SET_ERRORS = "SET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

// export const UPDATE_USER = "UPDATE_USER";

export const ADD_DEVICE = "ADD_DEVICE";

export const TRANSFER_OWNERSHIP = "TRANSFER_OWNERSHIP";

export const GET_DEVICES = "GET_DEVICES";

export const FETCH_DEVICES = "FETCH_DEVICES";

export const FETCH_ALERT_DEVICES = "FETCH_ALERT_DEVICES";

export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_INFO_BACK = "FETCH_INFO_BACK";
export const NOTINDATA = "NOTINDATA";
